# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
repos:
  - repo: local
    hooks:
      - id: bazel-mod-tidy
        name: format Bazel module files
        entry: bazel mod tidy
        language: system
        pass_filenames: false
        files: '(^|/)(MODULE\.bazel|.*\.bzl|BUILD(\.bazel)?)$'
      - id: bzlmod-lockfile
        name: bazel mod deps lockfile check
        entry: bazel mod deps --lockfile_mode=error
        language: system
        pass_filenames: false
        files: '(^|/)MODULE\.bazel(\.lock)?$'
      - id: actionlint
        name: actionlint
        # Disable shellcheck and pyflakes for now, to enforce consistent behavior.
        entry: .devcontainer/run-tool actionlint -shellcheck= -pyflakes=
        language: system
        require_serial: true
        types: [yaml]
        files: ^\.github/workflows/
      - id: generate-compile-commands
        name: bazel-compile-commands (for clang-tidy)
        entry: bazel-compile-commands --compiler /usr/bin/clang -R "-fno-canonical-system-headers=" -b '--define=pkcs11_lib=/dummy/path/to/make/pkcs11_lib_path/gen_rule/happy' //...
        language: system
        files: \.(c|cpp|h|hpp)$
        pass_filenames: false
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "--style=file"]
        files: \.(c|cpp|h|hpp)$
      - id: clang-tidy
        args: ["--config-file=.clang-tidy", "-p=$(pwd)", "--warnings-as-errors=*"]
        exclude: '(_test\.cpp|test_.*\.cpp)$'
  # Ensure every file has a copyright header as per the Eclipse Foundation's requirements
  # CR_CHECKER
  - repo: https://github.com/eclipse-score/tools
    rev: 7694bf823421b5542cd2f45239b8bdf205dbface
    hooks:
      - id: copyright
        args:
        - --exclusion-file=copyright_exclusions.txt
