# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Build and Test (Linux)

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
  workflow_dispatch: # Manual execution

jobs:
  tests:
    name: Build and Test (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x86_64, default backend
            bazel-target: "test //score/... --config=x86_64-linux"
            upload-name: "score_crypto linux x86_64 test results"
          - name: Linux aarch64, default backend
            bazel-target: "build //score/... --config=aarch64-linux -- -//score/cryptoki/..."
            upload-name: "NO UPLOAD OF TEST RESULTS CONFIGURED"
          - name: Linux x86_64, pkcs11 provider
            bazel-target: "test //score/... --config=x86_64-linux --//score/crypto/src/backend:score_crypto_score_backend_enabled=False"
            upload-name: "score_crypto linux x86_64 PKCS11 backend test results"
          - name: Linux x86_64, openssl provider
            bazel-target: "test //score/... --config=x86_64-linux --//score/crypto/src/backend:score_crypto_pkcs11_backend_enabled=False"
            upload-name: "score_crypto linux x86_64 OpenSSL backend test results"
    uses: eclipse-score/cicd-workflows/.github/workflows/tests.yml@8c48c65fc9e8927a06214192e6ebce520853087d
    with:
      bazel-target: ${{ matrix.bazel-target }}
      upload-name: ${{ matrix.upload-name }}
